### PR TITLE
More than two minor changes (misnomer)

### PR DESCRIPTION
**Pull request by jstavh**
The branch started out as two minor changes (ie deleted second package-lock.json), but then made more changes throughout the day. With astro files, the header remained even with page changes, but to do the same with markdown files, I ran the command yarn add react-markdown (and in the process of integrating). I changed layout, background color, text formats and added more pages. Since you took your picture off the about section, I refrained from adding details to these pages so far but can add details or images how you like. I was thinking of adding a mountainy background or backdrop instead of the one color background now (though it is the same as the header text). I am working on making the header touch both the right and left sides of the screen as well as the top.

### CODE REVIEW

**Comment by robinbb** [comment]
A primary motivation for using a SSG that converts .md files into HTML files is to allow us to separate concerns. Markdown files are concerned primarily with content. This PR does the opposite of the separation of concerns - it brings HTML together with content and styling. We should separate these, not bring them together. If we were willing to bring them together, we would not need a tool - we would simply write the code directly. Obviously, we want to avoid that. To achieve the styling changes that you make, here, find another (recommended) way of doing that. Perhaps the Astro docs have a hint. Perhaps you'll have to look to another SSG tool to learn about how to do that in principle.

**Review by robinbb — CHANGES_REQUESTED** [review]
Do not mix concerns.

**Review by jstavh — COMMENTED** [review]
I restructured the code as you suggested above. Some CSS is implemented and working on integrating more CSS

**Review by jstavh — COMMENTED** [review]
began adding pacific northwest forest color palette

**Review by jstavh — COMMENTED** [review]
I changed this branch to beyondDeploy and will make a separate branch for just deploying the home page

**Pull request merged**
