### PR TITLE
Mina FAQ page

### PR DESCRIPTION
**Pull request by robinbb**

### CODE REVIEW

**Comment by robinbb** [comment]
@jstavh At what URL/slug do you expect the new page to appear, in the preview? I think it's '/faq' but https://deploy-preview-39--granolateam.netlify.app/faq/ looks really terrible. Can you have a look?

**Comment by robinbb** [comment]
I merged Isaac's contributions into this branch (that has contributions from Jen and Jason). I'll do some additions, rewrites, and then maybe @JeffGranola can do some edits.

**Comment by jstavh** [comment]
> @jstavh At what URL/slug do you expect the new page to appear, in the preview? I think it's '/faq' but https://deploy-preview-39--granolateam.netlify.app/faq/ looks really terrible. Can you have a look?

@robinbb I will fix this. For right now, I made the FAQ page "draft true" as we think about how we want to navigate from the home page to this FAQ page.

**Comment by robinbb** [comment]
> @robinbb I will fix this. For right now, I made the FAQ page "draft true" as we think about how we want to navigate from the home page to this FAQ page.

Okay, but I want to publish this today after making my edits, but it does not render properly as you can see from the above URL. Can you provide a fix?

**Comment by jstavh** [comment]
> > @robinbb I will fix this. For right now, I made the FAQ page "draft true" as we think about how we want to navigate from the home page to this FAQ page.
> 
> Okay, but I want to publish this today after making my edits, but it does not render properly as you can see from the above URL. Can you provide a fix?

Yes, will do.

**Comment by jstavh** [comment]
> > > @robinbb I will fix this. For right now, I made the FAQ page "draft true" as we think about how we want to navigate from the home page to this FAQ page.
> > 
> > 
> > Okay, but I want to publish this today after making my edits, but it does not render properly as you can see from the above URL. Can you provide a fix?
> 
> Yes, will do.

@robinbb Fixed here and ready for your review: https://github.com/Granola-Team/site/pull/40

**Comment by jstavh** [comment]
@robinbb All fixed in recent commit and ready for your review.

**Pull request merged**
