### PR TITLE
Re-do home page with new logo

### PR DESCRIPTION
**Pull request by jstavh**
For re-doing the home page, I created it similar to the one in the Editable.ai file page 3 (that can be found in the Granola Dropbox -> Granola Graphics -> Brand Guide). I added the logo to the public folder and integrated it into the component, did some CSS configuring after changing the SCSS for hero and global (in particular, I noticed that the logo on page 3 in Editable.ai appears much larger than granola, so I tried to change dimensions a bit in the CSS file but also wanted it to be pretty so keep it at a 60% height 40% width).

### CODE REVIEW

**Review by trevorbernard — DISMISSED** [review]
You shouldn't be commiting package-lock.json into the repo

**Comment by trevorbernard** [comment]
In the preview, the logo is broken

**Comment by jstavh** [comment]
I added package-lock.json to gitignore and changed the path for the image so it is appearing in the preview now.

**Comment by robinbb** [comment]
I had to do this, but I disagree with Trevor. I believe that lock files (that pin dependency packages) should indeed be added to the repo. However, there is no need to discuss this here in this PR.

**Review by robinbb — APPROVED** [review]

**Pull request merged**
